"""
Django settings for AtThirty project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from AtThirty.base import *

###############################################################
#项目配置
###############################################################
# Global Module Name configuration
MODULES = ['blog','sysAdmin','note']

INSTALLED_APPS += tuple(["app."+i for i in MODULES])
#INSTALLED_APPS += ('app.blog','app.sysAdmin',)


TEMPLATES[0]['DIRS'] = [os.path.join(os.path.join(BASE_DIR, "templates"),i) for i in MODULES] 
'''
TEMPLATES [{...., 
            'DIRS': [os.path.join(os.path.join(BASE_DIR, "templates"),"blog"),
                os.path.join(os.path.join(BASE_DIR, "templates"),"sysAdmin"),
                ]
            
        ...,
}]
'''
STATICFILES_DIRS += tuple([os.path.join(os.path.join(BASE_DIR, "static"),i) for i in MODULES])
'''
STATICFILES_DIRS += (os.path.join(os.path.join(BASE_DIR, "static"),"blog"),
os.path.join(os.path.join(BASE_DIR, "static"),"sysAdmin"),
)
'''

#DEBUG = False
#ALLOWED_HOSTS = ['localhost']

